version: "3.8"

services:
    app1:
        build:
            context: .
        image: communication-server
        env_file:
            - .env
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        networks:
            - postgres-network
            - redis-network
            - nginx-network
        depends_on:
            - postgres
            - redis
        restart: unless-stopped

    app2:
        build:
            context: .
        image: communication-server
        env_file:
            - .env
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        networks:
            - postgres-network
            - redis-network
            - nginx-network
        depends_on:
            - postgres
            - redis
        restart: unless-stopped

    nginx:
        image: nginx:1.23.1-alpine
        ports:
            - 80:80
        environment:
            - NGINX_HOST=127.0.01,localhost
            - NGINX_PORT=80
            - APP_HOST_1=app1
            - APP_HOST_2=app2
            - APP_PORT=${APP_PORT}
        volumes:
            - ./.docker/nginx/templates:/etc/nginx/templates
        networks:
            - nginx-network
        depends_on:
            - app1
            - app2
        restart: unless-stopped

    postgres:
        image: postgres:14.1-alpine3.15
        environment:
            - POSTGRES_DB=${DATABASE_DB}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        networks:
            - postgres-network
        restart: unless-stopped

    adminer:
        image: dockette/adminer:pgsql
        ports:
        - 8081:80
        networks:
            - postgres-network
        depends_on:
            - postgres
        restart: unless-stopped

    redis:
        image: redis:6.2.5-alpine3.14
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
            - redis-network
        restart: unless-stopped

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - 8082:8081
        networks:
            - redis-network
        depends_on:
            - redis
        restart: unless-stopped

networks:
    postgres-network:
    redis-network:
    nginx-network:
